name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: g++ -std=c++17 Lab3Var4/Source.cpp -o program.out -fopenmp
    - name: execute
      run: ./program.out
